// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gykadoptlurvnmimejlm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5a2Fkb3B0bHVydm5taW1lamxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY3OTc2NjQsImV4cCI6MjA1MjM3MzY2NH0.9jBXFdhdcyF3rvT3eyooTqiEl4I6KroK-jZchYbJpFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);